services:
  radarr: 
      image: lscr.io/linuxserver/radarr:latest 
      container_name: radarr 
      hostname: radarr 
      networks: 
        - proxy 
      environment: 
        - PUID=${PUID} 
        - PGID=${PGID} 
        - TZ=${TZ} 
      volumes: 
        - ./config:/config 
        - "/media/inigo/My Passport/Media_Server/torrent_downloads:/downloads" 
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.rule=Host(`${TRAEFIK_RADARR}`)"
        - "traefik.http.routers.radarr.entrypoints=https"
        - "traefik.http.routers.radarr.tls=true"  
        - "traefik.http.routers.radarr.tls.certresolver=mydnschallenge"
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
        # Watchtower Update
        - "com.centurylinklabs.watchtower.enable=true" 
networks:
  proxy:
    external: true