services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`${TRAEFIK_BAZARR}`)"
      - "traefik.http.routers.bazarr.entrypoints=https"
      - "traefik.http.routers.bazarr.tls=true"  
      - "traefik.http.routers.bazarr.tls.certresolver=mydnschallenge"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true" 
networks:
  proxy:
    external: true 